In [1]:

import pandas as pd

In [103]:
df = pd.read_csv("csv_full_fingerprint/Aria/file_Aria_7.csv",header=None, delimiter = '\t')
print (df.head())

   0   1   2   3    4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0   0   0   0   1    0   0   0   0   1   0  ...   0   0   0   0   0   0   0
1   0   0   0   1    0   0   0   0   1   0  ...   0   0   0   0   0   0   0
2   0   0   0   0  308   0   0   0   2   1  ...   1   0   0   1   1   0   0
3   0   0   0   0  308   0   0   0   3   1  ...   1   0   0   1   1   0   0
4   0   0   0   0  308   0   0   0   3   1  ...   1   0   0   1   1   0   0

   21  22    23
0   0   0  Aria
1   0   0  Aria
2   0   0  Aria
3   0   0  Aria
4   0   0  Aria

[5 rows x 24 columns]

In [102]:
# select 12 unique vector fingerprints

df = df.drop_duplicates()
df = df[:12]
print(df.shape)
print(df.head())

(12, 24)
   0   1   2   3    4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0   0   0   0   1    0   0   0   0   1   0  ...   0   0   0   0   0   0   0
2   0   0   0   0  308   0   0   0   2   1  ...   1   0   0   1   1   0   0
3   0   0   0   0  308   0   0   0   3   1  ...   1   0   0   1   1   0   0
6   0   1   0   0    0   0   0   0   3   0  ...   0   0   0   0   0   0   0
9   0   0   0   0   40   0   0   0   4   3  ...   1   0   0   0   0   0   1

   21  22    23
0   0   0  Aria
2   0   0  Aria
3   0   0  Aria
6   0   0  Aria
9   0   0  Aria

[5 rows x 24 columns]

In [113]:
# combine data
import glob

path = r'csv_full_fingerprint/Aria' # use your path
all_files = glob.glob(path + "/*.csv")

li = {}
i = 1
for filename in all_files:
    df = pd.read_csv(filename, index_col=None,header=None, delimiter = '\t')
    df = df.drop_duplicates()
    df = df[:12]
    li[i]= df
    #li.append(df)
    print(filename)
    i+=1
print(i)
frame = pd.concat(li, axis=0)

csv_full_fingerprint/Aria\file_Aria_1.csv
csv_full_fingerprint/Aria\file_Aria_10.csv
csv_full_fingerprint/Aria\file_Aria_11.csv
csv_full_fingerprint/Aria\file_Aria_12.csv
csv_full_fingerprint/Aria\file_Aria_13.csv
csv_full_fingerprint/Aria\file_Aria_14.csv
csv_full_fingerprint/Aria\file_Aria_15.csv
csv_full_fingerprint/Aria\file_Aria_16.csv
csv_full_fingerprint/Aria\file_Aria_17.csv
csv_full_fingerprint/Aria\file_Aria_18.csv
csv_full_fingerprint/Aria\file_Aria_19.csv
csv_full_fingerprint/Aria\file_Aria_2.csv
csv_full_fingerprint/Aria\file_Aria_3.csv
csv_full_fingerprint/Aria\file_Aria_4.csv
csv_full_fingerprint/Aria\file_Aria_5.csv
csv_full_fingerprint/Aria\file_Aria_6.csv
csv_full_fingerprint/Aria\file_Aria_7.csv
csv_full_fingerprint/Aria\file_Aria_8.csv
csv_full_fingerprint/Aria\file_Aria_9.csv
20

In [117]:
frame.size

11232

In [114]:
# combine data
import glob

path = r'csv_full_fingerprint/D-LinkCam' # use your path
all_files = glob.glob(path + "/*.csv")

#li = {}
i = 20
for filename in all_files:
    df = pd.read_csv(filename, index_col=None,header=None, delimiter = '\t')
    df = df.drop_duplicates()
    df = df[:12]
    li[i]= df
    #li.append(df)
    print(filename)
    i+=1
print(i)
frame = pd.concat(li, axis=0)

csv_full_fingerprint/D-LinkCam\file_D-LinkCam_20.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_21.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_22.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_23.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_24.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_25.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_26.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_27.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_28.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_29.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_30.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_31.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_32.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_33.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_34.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_35.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_36.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_37.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_38.csv
csv_full_fingerprint/D-LinkCam\file_D-LinkCam_39.csv
40

In [118]:
# oneclass SVM classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.svm import OneClassSVM
from sklearn.datasets import make_classification

In [119]:
X = frame.loc[:,:22]
y = frame.loc[:,23]
#y.head(), X.head()

In [120]:
X

       0   1   2   3    4   5   6   7   8   9   ...  13  14  15  16  17  18  \
1  0    0   0   0   1    0   0   0   0   1   0  ...   0   0   0   0   0   0
   2    0   0   0   0  308   0   0   0   2   1  ...   0   1   0   0   1   1
   3    0   0   0   0  308   0   0   0   3   1  ...   0   1   0   0   1   1
   6    0   1   0   0    0   0   0   0   3   0  ...   0   0   0   0   0   0
   9    0   0   0   0   40   0   0   0   4   3  ...   0   1   0   0   0   0
...    ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
39 9    0   0   0   0   24   0   0   0   4   0  ...   0   0   0   0   0   0
   12   0   0   0   0  127   0   0   0   4   2  ...   0   1   0   0   0   0
   13   0   0   0   0  131   0   0   0   4   2  ...   0   1   0   0   0   0
   14   0   0   0   0  135   0   0   0   4   2  ...   0   1   0   0   0   0
   16   0   1   0   0    0   0   0   0   4   0  ...   0   0   0   0   0   0

       19  20  21  22
1  0    0   0   0   0
   2    0   0   0   0
   3    0   0   0   0
   6    0   0   0   0
   9    0   1   0   0
...    ..  ..  ..  ..
39 9    0   0   0   0
   12   0   0   1   0
   13   0   0   1   0
   14   0   0   1   0
   16   0   0   0   0

[468 rows x 23 columns]

In [121]:
trainX[trainy[:].isin(['Aria'])]

,,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
19,14,0,0,0,0,116,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0
9,15,0,0,0,0,20,0,0,0,5,1,...,1,0,0,1,0,0,0,0,0,0
17,11,0,0,0,0,40,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0
8,14,0,0,0,0,20,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0
5,10,0,0,0,0,119,0,0,0,4,1,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,11,0,0,0,0,40,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0
19,9,0,0,0,0,40,0,0,0,4,3,...,0,1,0,0,0,0,0,1,0,0
16,15,0,0,0,0,44,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0
18,2,0,0,0,0,308,0,0,0,2,1,...,0,1,0,0,1,1,0,0,0,0
8,15,0,0,0,0,116,0,0,0,5,3,...,1,0,0,1,0,0,0,0,0,0

NameError: name 'X' is not defined

In [128]:
clf = OneClassSVM(gamma='auto').fit(X)
clf.predict(X)
clf.score_samples(X)

array([19.07617096, 19.07647573, 19.13847521, 20.39789057, 19.07589533,
        2.        , 19.0758954 , 19.07606137, 19.07587557, 19.07598683,
       19.0762719 , 19.0761791 , 19.07617096, 19.07647573, 19.13847521,
       20.39789057, 19.07589533, 19.07636121, 19.0758954 , 19.07606137,
       19.07587557, 19.07598683, 19.0762719 , 19.0761791 , 19.07617096,
       19.07647573, 19.13847521, 20.39789057, 19.07589533, 19.07636121,
       19.0758954 , 19.07606137, 19.07587557, 19.07598683, 19.0761791 ,
       19.0762719 , 19.07617096, 19.07647573, 19.13847521, 20.39789057,
       19.07589533, 19.07636121, 19.0758954 , 19.07606137, 19.07587557,
       19.07598683, 19.0762719 , 19.0761791 , 19.07617096, 19.07647573,
       19.13847521, 20.39789057, 19.07589533, 19.07636121, 19.0758954 ,
       19.07606137, 19.07587557, 19.07598683, 19.0762719 , 19.0761791 ,
       19.07617096, 19.07647573, 19.13847521, 20.39789057, 19.07589533,
       19.07636121, 19.0758954 , 19.07606137, 19.07587557, 19.07598683,
       19.0762719 , 19.0761791 , 19.07617096, 19.07647573, 19.13847521,
       20.39789057, 19.07589533, 19.07636121, 19.0758954 , 19.07606137,
       19.07587557, 19.07598683, 19.0762719 , 19.0761791 , 19.07617096,
       19.07647573, 13.43899678, 19.13847521, 20.39789057, 19.07589533,
       19.07636121, 19.0758954 , 19.07606137, 19.07587557, 19.07598683,
       19.0762719 , 19.07617096, 19.07647573, 19.13847521, 20.39789057,
       19.07589533, 19.07636121, 19.0758954 , 19.07606137, 19.07587557,
       19.07598683, 19.0761791 , 19.0762719 , 19.07617096, 19.07647573,
       19.13847521, 20.39789057, 19.07589533, 19.07636121, 19.0758954 ,
       19.07606137, 19.07587557, 19.07598683, 19.0762719 , 19.0761791 ,
       19.07617096, 19.07647573, 19.13847521, 20.39789057, 19.07589533,
       19.07636121, 19.0758954 , 19.07606137, 19.07587557, 19.07598683,
       19.0762719 , 19.0761791 , 19.07617096, 19.07647573, 19.13847521,
       20.39789057, 19.07589533, 19.07636121, 19.0758954 , 19.07606137,
       19.07587557, 19.07598683, 19.0761791 , 19.0762719 , 19.07617096,
       19.07647573, 19.13847521, 20.39789057, 19.07589533,  2.        ,
       19.0758954 , 19.07606137, 19.07587557, 19.07598683, 19.0762719 ,
       19.0761791 , 19.07617096, 19.07647573, 19.13847521, 20.39789057,
       19.07589533, 19.07636121, 19.0758954 , 19.07606137, 19.07587557,
       19.07598683, 19.0762719 , 19.0761791 , 19.07617096, 19.07647573,
       19.13847521, 20.39789057, 19.07589533, 19.07636121, 19.0758954 ,
       19.07606137, 19.07587557, 19.07598683, 19.0762719 , 19.0761791 ,
       19.07617096, 19.07647573, 19.13847521, 20.39789057, 19.07589533,
       19.07636121, 19.0758954 , 19.07606137, 19.07587557, 19.07598683,
       19.0762719 , 19.0761791 , 19.07617096, 19.07647573, 19.13847521,
       20.39789057, 19.07589533, 19.07636121, 19.0758954 , 19.07606137,
       19.07587557, 19.07598683, 19.0762719 , 19.0761791 , 19.07617096,
       19.07647573, 19.13847521, 20.39789057, 19.07589533, 19.07636121,
       19.0758954 , 19.07606137, 19.07587557, 19.07598683, 19.0762719 ,
       19.0761791 , 19.07617096, 19.07647573, 19.13847521, 20.39789057,
       19.07589533, 19.07636121, 19.0758954 , 19.07606137, 19.07587557,
       19.07598683, 19.0762719 , 19.0761791 , 19.07617096, 19.07668545,
       18.61708031, 20.33387342, 17.98174506, 17.68350553, 17.68591928,
       19.07646784, 19.07677788, 19.07636126, 19.25032022, 13.21997584,
       19.07617096, 19.07668545, 18.61708031, 20.33387342, 19.13847521,
       19.07677616, 19.07646784, 19.07677788, 19.07636126, 19.14149738,
       13.21997584, 18.10212324, 19.07617096, 19.07668545, 20.33387342,
       18.61708031, 19.13847521, 19.07677616, 19.07646784, 19.07677788,
       19.07636126, 19.14149738, 13.21997584, 18.10212324, 19.07617096,
       19.07668545, 20.33387342, 18.61708031, 19.13847521, 19.07677616,
       19.07646784, 19.07677788, 19.07636126, 19.25032022, 19.36727607,
       14.24733518, 19.07617096, 19.07668545, 20.33387342, 18.61708031,
        1.95745337, 19.13847521, 19.07677616, 19.07646784, 19.07677788,
       19.07636126, 19.14149738, 19.36727607, 19.07617096, 19.07668545,
       18.61708031, 20.33387342, 17.98174506, 17.68350553, 17.68591928,
       19.07646784, 19.07677788, 19.07636126, 19.25032022, 13.21997584,
       19.07617096, 19.07668545, 18.61708031, 20.33387342, 19.13847521,
       19.07677616, 19.07646784, 19.07677788, 19.07636126, 19.14149738,
       19.36727607, 14.24733518, 19.07617096, 19.07668545, 20.33387342,
       18.61708031, 19.13847521, 19.07677616, 19.07646784, 19.07677788,
       19.07636126, 19.14149738, 13.21997584, 18.10212324, 19.07617096,
       19.07668545, 20.33387342, 18.61708031, 19.13847521, 19.07677616,
       19.07646784, 19.07677788, 19.07636126, 19.25032022, 13.21997584,
       16.71811244, 19.07617096, 18.89930441, 19.07668545, 18.61708031,
       20.33387342, 19.13847521, 19.07677616, 19.07646784, 19.07677788,
       19.07636126, 19.14149738, 13.21997584, 19.07617096, 19.07647573,
       18.95032729, 19.07684125, 20.39789057, 18.57453368, 19.07677788,
       14.69173652, 12.00965895, 19.07636126, 19.14149738, 13.21997584,
       19.07617096, 19.07647573, 18.95032729, 19.07684125, 19.07677788,
       14.69173652, 14.87457096, 12.00965895, 19.07636126, 19.14149738,
       13.21997584, 10.40524961, 19.07617096, 19.07647573, 19.07684125,
       18.57453368, 20.39789057, 19.07677616,  1.00064399,  1.00064399,
        1.84039812,  1.8408329 , 19.36727607,  1.        , 19.07617096,
       19.07647573, 18.95032729, 19.07684125, 18.57453368, 20.39789057,
       19.07646784, 19.07677788, 14.69173652, 12.00965895, 19.07636126,
       19.25032022, 19.07617096, 19.07647573, 18.95032729, 19.07684125,
       20.39789057, 18.57453368, 19.07646784, 19.07677788, 14.69173652,
       12.00965895, 19.07636126, 19.14149738, 19.07617096, 19.07647573,
       19.07684125, 19.07677616, 20.39789057, 18.57453368, 10.20358293,
       19.07677788, 14.69173652, 14.87457096, 19.07636126, 19.25032022,
       19.07617096, 19.07647573, 19.07684125, 19.07677616, 20.39789057,
       18.57453368, 19.07646784, 19.07677788, 14.69173652, 12.00965895,
       19.07636126, 19.14149738, 19.07617096, 19.07647573, 19.07684125,
       20.39789057, 18.57453368, 19.07677616, 19.07646784, 19.07677788,
       14.69173652, 14.87457096, 12.00965895, 19.07636126, 19.07617096,
       19.07647573,  1.95745337, 19.07677616, 19.07684125, 20.39789057,
       18.57453368, 19.07677788, 14.69173652, 14.87457096, 12.00965895,
       19.07636126, 19.07617096, 19.07647573, 19.07684125, 19.07677616,
       18.57453368, 20.39789057, 19.07646784, 19.07677788, 14.69173652,
       14.87457096, 12.00965895, 19.07636126])

In [127]:
# split into train/test sets
trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.5, random_state=2, stratify=y)
# define outlier detection model
model = OneClassSVM(gamma='scale', nu=0.01)
# fit on majority class
trainX = trainX[trainy[:].isin(['Aria'])]
model.fit(trainX)
# detect outliers in the test set
yhat = model.predict(testX)

In [ ]:
# mark inliers 1, outliers -1
testy[testy[:].isin(['D-LinkCam'])] = -1
testy[testy[:].isin(['Aria'])] = 1
# calculate score
score = f1_score(testy, yhat, pos_label=-1)
print('F1 Score: %.3f' % score)